// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelDB;

namespace SPA_NetCore_Foundation06.Migrations
{
    /// <summary>
    /// 
    /// </summary>
    [DbContext(typeof(SpaNetCoreFoundationContext))]
    [Migration("20200211195240_UserInfo_Add")]
    partial class UserInfo_Add
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ModelDB.User", b =>
                {
                    b.Property<long>("idUser")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("SignEmail");

                    b.HasKey("idUser");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            idUser = 1L,
                            Password = "1111",
                            SignEmail = "test01@email.net"
                        },
                        new
                        {
                            idUser = 2L,
                            Password = "1111",
                            SignEmail = "test02@email.net"
                        },
                        new
                        {
                            idUser = 3L,
                            Password = "1111",
                            SignEmail = "testuser@email.net"
                        },
                        new
                        {
                            idUser = 4L,
                            Password = "1111",
                            SignEmail = "user@email.net"
                        });
                });

            modelBuilder.Entity("ModelDB.UserInfo", b =>
                {
                    b.Property<long>("idUserInfo")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ManagerPermission");

                    b.Property<string>("ViewName")
                        .HasMaxLength(16);

                    b.Property<long>("idUser");

                    b.HasKey("idUserInfo");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            idUserInfo = 1L,
                            ManagerPermission = 2147483647,
                            ViewName = "root",
                            idUser = 1L
                        },
                        new
                        {
                            idUserInfo = 2L,
                            ManagerPermission = 1,
                            ViewName = "admin",
                            idUser = 2L
                        },
                        new
                        {
                            idUserInfo = 3L,
                            ManagerPermission = 1,
                            ViewName = "test User",
                            idUser = 3L
                        },
                        new
                        {
                            idUserInfo = 4L,
                            ManagerPermission = 0,
                            ViewName = "User",
                            idUser = 4L
                        });
                });

            modelBuilder.Entity("ModelDB.UserSignIn", b =>
                {
                    b.Property<long>("idUserSignIn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("RefreshDate");

                    b.Property<string>("RefreshToken");

                    b.Property<DateTime>("SignInDate");

                    b.Property<long>("idUser");

                    b.HasKey("idUserSignIn");

                    b.ToTable("UserSignIn");
                });
#pragma warning restore 612, 618
        }
    }
}
